import { BytesCoder, Flattable, ITypeBuilder, OptionalTypeBuilder, Sha512, Tagged, ValueTypeBuilder } from '@stevenkellner/typescript-common-functionality';
import { Team } from './Team';
import { Person } from './Person';

/**
 * Represents an invitation to join a team.
 *
 * An invitation can be team-wide (personId is null) or specific to a person.
 * The invitation ID is generated by hashing the team ID and optional person ID.
 */
export class Invitation implements Flattable<Invitation.Flatten> {

    /**
     * Creates a new Invitation instance.
     *
     * @param teamId - The ID of the team for the invitation
     * @param personId - Optional person ID for person-specific invitations (null for team-wide invitations)
     */
    constructor(
        public teamId: Team.Id,
        public personId: Person.Id | null
    ) {}

    /**
     * Creates a unique invitation ID by hashing the team ID and optional person ID.
     *
     * Uses SHA-512 hashing and takes the first 12 characters of the hex representation.
     * Team-wide invitations (personId null) hash only the team ID.
     * Person-specific invitations hash both team ID and person ID concatenated.
     *
     * @returns Tagged invitation ID string (12 hex characters)
     */
    public createId(): Invitation.Id {
        const hasher = new Sha512();
        const teamIdBytes = BytesCoder.fromUtf8(this.teamId.guidString);
        let invitationBytes = teamIdBytes;
        if (this.personId !== null) {
            const personIdBytes = BytesCoder.fromUtf8(this.personId.guidString);
            invitationBytes = new Uint8Array([...teamIdBytes, ...personIdBytes]);
        }
        const hashedInvitationBytes = hasher.hash(invitationBytes);
        const rawId = BytesCoder.toHex(hashedInvitationBytes).slice(0, 12);
        return new Tagged(rawId, 'invitation');
    }

    /**
     * Returns the flattened representation for serialization.
     */
    public get flatten(): Invitation.Flatten {
        return {
            teamId: this.teamId.flatten,
            personId: this.personId !== null ? this.personId.flatten : null
        };
    }
}

export namespace Invitation {

    /**
     * Tagged string type for invitation identifiers (12 hex characters).
     */
    export type Id = Tagged<string, 'invitation'>;

    export namespace Id {

        /**
         * Flattened representation of an invitation ID (string).
         */
        export type Flatten = string;

        /**
         * Type builder for Invitation.Id serialization/deserialization.
         */
        export const builder = Tagged.builder('invitation' as const, new ValueTypeBuilder<string>());
    }

    /**
     * Flattened representation of an Invitation for serialization.
     */
    export type Flatten = {
        teamId: Team.Id.Flatten,
        personId: Person.Id.Flatten | null
    };

    /**
     * Type builder for Invitation serialization/deserialization.
     */
    export class TypeBuilder implements ITypeBuilder<Flatten, Invitation> {

        /**
         * Builds an Invitation instance from flattened data.
         *
         * @param value - Flattened invitation data
         * @returns Invitation instance
         */
        public build(value: Flatten): Invitation {
            return new Invitation(
                Team.Id.builder.build(value.teamId),
                new OptionalTypeBuilder(Person.Id.builder).build(value.personId)
            );
        }
    }

    /**
     * Singleton instance of TypeBuilder for Invitation.
     */
    export const builder = new TypeBuilder();
}
