name: Publish Node.js Package

on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    name: "Publish Node.js Package to NPM"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - working-directory: functions
        run: npm ci
      - working-directory: functions
        run: npm run rebuild
      - working-directory: functions
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    name: "Create Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name}}
          release_name: Release ${{ github.ref_name }}
